apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: unknown-beetle-python-gitops
  description: This is GitOps manifest for unknown-beetle-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: unknown-beetle-python
    janus-idp.io/tekton: unknown-beetle-python 
    backstage.io/kubernetes-id: unknown-beetle-python 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:unknown-beetle-python
