apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: unknown-beetle-python
  janus-idp.io/tekton: unknown-beetle-python
  backstage.io/kubernetes-id: unknown-beetle-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: unknown-beetle-python
resources: 
- deployment.yaml
- route.yaml
- service.yaml
